export const cssColorProperties = {
  text: "--color-text",
  decorationPrimary: "--color-deco-pri",
  decorationSecondary: "--color-deco-sec",
  revertedText: "--color-rev-text",
  em1: "--color-em1",
  em2: "--color-em2",
  em3: "--color-em3",
  em4: "--color-em4",
  em1Dim: "--color-em1-dim",
  em2Dim: "--color-em2-dim",
  em3Dim: "--color-em3-dim",
  em4Dim: "--color-em4-dim",
  bgPrimary: "--color-bg-pri",
  bgRevPrimary: "--color-bg-rev-pri",
  bgEm1: "--color-bg-em1",
  bgComment: "--color-bg-comment",
  bgInput: "--color-bg-input",
  brandWikipedia: "--color-brand-wikipedia",
  brandEncyclopediaOfMath: "--color-brand-eom",
  skeletonPrimary: "--color-skeleton-pri",
};

export const cssColors = {
  text: `var(${cssColorProperties.text})`,
  decorationPrimary: `var(${cssColorProperties.decorationPrimary})`,
  decorationSecondary: `var(${cssColorProperties.decorationSecondary})`,
  revertedText: `var(${cssColorProperties.revertedText})`,
  em1: `var(${cssColorProperties.em1})`,
  em2: `var(${cssColorProperties.em2})`,
  em3: `var(${cssColorProperties.em3})`,
  em4: `var(${cssColorProperties.em4})`,
  em1Dim: `var(${cssColorProperties.em1Dim})`,
  em2Dim: `var(${cssColorProperties.em2Dim})`,
  em3Dim: `var(${cssColorProperties.em3Dim})`,
  em4Dim: `var(${cssColorProperties.em4Dim})`,
  bgPrimary: `var(${cssColorProperties.bgPrimary})`,
  bgRevPrimary: `var(${cssColorProperties.bgRevPrimary})`,
  bgEm1: `var(${cssColorProperties.bgEm1})`,
  bgComment: `var(${cssColorProperties.bgComment})`,
  bgInput: `var(${cssColorProperties.bgInput})`,
  brandWikipedia: `var(${cssColorProperties.brandWikipedia})`,
  brandEncyclopediaOfMath: `var(${cssColorProperties.brandEncyclopediaOfMath})`,
  skeletonPrimary: `var(${cssColorProperties.skeletonPrimary})`,
};
