tags = [
  "線形代数",
  "基礎",
]
chapters = [
  "matrix",
  "matrix-basic-definitions",
  "matrix-multiplication",
  "matrix-determinant",
  "matrix-cofactor",
  "cramers-rule",
  "linear-space",
  "linear-combination",
  "linear-map",
  "matrix-trace",
  "inner-product",
  "inner-product2",
  "eigenvalue",
]
